# A single quote ' and a double quote "
output1 = ...

# A forward slash / and a backward slash \
output2 = ...

# Three single quotes ''' and three double quotes """
output3 = ...

# Double forward slash // and Double backward slash \\
output4 = ...